# chp2. sklearn 으로 시작하는 ML

## sikit-learn의 소개 및 특징

* 머신러닝 대표적인 라이브러리
* 사용하기 쉬움

In [1]:
import sklearn
print(sklearn.__version__)

0.23.2


## first. 붓꽃 품종 예측하기

- feature 속성: dataset의 일반 속성, 타겟갑을 제외한 나머지 속성을 모두 feature로 저장
- label, class, target, decision: 정답 데이터, 지도학습 중 분류의 경우 label or class로 지칭

In [2]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [4]:
iris = load_iris()

In [5]:
# iris.data는 iris dataset에서 feature만으로 된 데이터를 numpy로 가지고 있음
iris_data = iris.data

In [6]:
iris_label = iris.target

In [7]:
print('iris target:', iris_label)

iris target: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [8]:
print('iris target name:', iris.target_names)

iris target name: ['setosa' 'versicolor' 'virginica']


In [9]:
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target

In [10]:
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [11]:
# train_test_split을 이용하면 쉽게 train 과 test로 나눌 수 있습니다. test_size =0.2 는 테스트 데이터 20%, 학습데이터 80%로 나눌 수 있습니다.
# random_state는 random을 부여하는 seed의 의미이다. 난수 값을 일정하게 하기위해 random_state를 지정해 줄 수 있습니다.
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

In [12]:
# DecisionTreeClassifier객체 생성
dt_clt = DecisionTreeClassifier(random_state=11)

In [13]:
# 학습시키기
dt_clt.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [14]:
# test 값을 넣고 값을 확인
pred = dt_clt.predict(X_test)

In [15]:
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [16]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0: .4f}'.format(accuracy_score(y_test, pred)))

예측 정확도:  0.9333


## 사이킷런의 기반 프레임워크 익히기

* 모델학습 메서드: fit()
* 예측 메서드 : predict()
* 분류 + 회귀 클래스 : Estimator
* 분류 알고리즘 클래스: Classifier
* 회귀 알고리즘 클래스: Regressor

In [17]:
print(type(iris))

<class 'sklearn.utils.Bunch'>


In [18]:
keys = iris.keys()
keys

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [19]:
print('type of feature_names:', type(iris.feature_names))
print('shape of feature_names:', len(iris.feature_names))
print(iris.feature_names)

type of feature_names: <class 'list'>
shape of feature_names: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [20]:
print('Type of target_names:', type(iris.target_names))
print('Shape of target_names:', len(iris.target_names))
print(iris.target_names)

Type of target_names: <class 'numpy.ndarray'>
Shape of target_names: 3
['setosa' 'versicolor' 'virginica']


In [21]:
print('Type of data:', type(iris.data))
print('Shape of data:', iris.data.shape)
print(iris['data'])

Type of data: <class 'numpy.ndarray'>
Shape of data: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3

In [22]:
print('Type of target:', type(iris.target))
print('Shape of target:', iris.target.shape)
print(iris.target)

Type of target: <class 'numpy.ndarray'>
Shape of target: (150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


## train, test data 분리 - train_test_split()

In [23]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data, train_label)

# 학습 데이터 셋으로 예측 수행, 하지만 모든 값을 넣고 했기 때문에 정확할 수 밖에 없다.
pred = dt_clf.predict(train_data)
print('정확도:', accuracy_score(train_label, pred))

정확도: 1.0


In [33]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

dt_clf = DecisionTreeClassifier()
iris_data = load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target,
                                                    test_size=0.3, random_state=121)

dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print('예측 정확도: {0: .4f}'.format(accuracy_score(y_test, pred)))

예측 정확도:  0.9556


### numpy ndarray 뿐만 아니라 pandas DataFrame/Series도 train_test_split() 가능

In [34]:
import pandas as pd

iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [39]:
ftr_df = iris_df.iloc[:, : -1] # 행은 모두, 그리고 열은 하나(target)를 빼고 다
tgt_df = iris_df.iloc[:, -1] # 행은 모두, 그리고 열은 하나(target)만 넣기
X_train, X_test, y_train, y_test = train_test_split(ftr_df, tgt_df,
                                                   test_size = 0.3, random_state = 121)

In [40]:
print(type(X_train), type(y_test), type(y_train), type(y_test))

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'> <class 'pandas.core.series.Series'> <class 'pandas.core.series.Series'>


In [43]:
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print('예측 정확도: {0: .4f}'.format(accuracy_score(y_test, pred)))

예측 정확도:  0.9556
