# chap2. sklearn으로 수행하는 ML

## 데이터 전처리

- 데이터 클렌징
- 결손값 처리
- 데이터 인코딩 (label, one-hot incoding)
- 데이터 스케일링
- 이상치 제거
- feature 선택, 추출 및 가공

### 데이터 인코딩

#### label incoding: 데이터의 index를 숫자로 변환

In [3]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 2 2]


In [4]:
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [6]:
print('디코딩 원본 값:', encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))


디코딩 원본 값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


#### one-hot incoding

In [8]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

labels = labels.reshape(-1, 1) # 이게 중요함, 상당히 귀찮음

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(7, 6)


In [9]:
import pandas as pd

df = pd.DataFrame({'itiem': ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서']})
df

itiem
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5     믹서
6     믹서

In [11]:
pd.get_dummies(df) # 더 쉽게 가능

itiem_TV  itiem_냉장고  itiem_믹서  itiem_선풍기  itiem_전자레인지  itiem_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         1          0            0          0
6         0          0         1          0            0          0

### 피처 스케일링과 정규화 

- 표준화: 데이터의 피처 각각이 평균이 0이고 분산인 1인 가우시안 정규 분포를 가진 값을 변환하는 것을 의미한다. (StandardScaler)
- 정규화: 서로 다른 피처의 크기를 통일하기 위해 크기를 변환해주는 개념. ( 

#### StandardScaler

In [20]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns= iris.feature_names)

print('<feature 평균값>\n',iris_df.mean())
print('\n<feature 분산값>\n', iris_df.var())

<feature 평균값>
 sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

<feature 분산값>
 sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('<feature 평균값>\n',iris_df_scaled.mean()) # 거의 0임
print('\n<feature 분산값>\n', iris_df_scaled.var()) # 거의 1임

<feature 평균값>
 sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

<feature 분산값>
 sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


#### MinMaxScaler

In [23]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('<feature 최소값>\n',iris_df_scaled.min()) # 거의 0임
print('\n<feature 최대값>\n', iris_df_scaled.max()) # 거의 1임

<feature 최소값>
 sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

<feature 최대값>
 sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
